name: release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup | Ensure registry access
        run: npm whoami
      - name: Install dependencies
        run: yarn
      - name: Typecheck
        run: yarn typecheck
      - name: Bundle
        run: yarn bundle
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        run: npm publish
